name: Build Android APK

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Check initial disk usage
      - name: Check available disk space after cleanup
        run: df -h

      # Step 3: Define Version Manually
      - name: Set Version Manually
        run: echo "VERSION=0.0.1" >> $GITHUB_ENV

      # Step 4: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      # Step 5: Set up JDK for Android builds
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"

      # Step 6: Install dependencies
      - name: Install dependencies
        run: yarn

      # Step 7: Load assets for the Android build
      - name: Load assets
        run: |
          npx react-native bundle \
          --platform android \
          --dev false \
          --entry-file index.js \
          --bundle-output android/app/src/main/assets/index.android.bundle \
          --assets-dest android/app/src/main/res

      # Step 8: Build APKs for different environments
      - name: Build Dev APK
        run: |
          cd android
          ./gradlew assembleDevRelease

      # Step 9: Rename APK with version
      - name: Rename APK with Version
        run: |
          mv android/app/build/outputs/apk/dev/release/app-dev-release.apk \
             android/app/build/outputs/apk/dev/release/app-dev-release-v${{ env.VERSION }}.apk

      # Step 10: Upload APK as a build artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-dev-release-v${{ env.VERSION }}.apk
          path: android/app/build/outputs/apk/dev/release/app-dev-release-v${{ env.VERSION }}.apk
