name: React Native CI Pipeline

on:
  push:
    branches:
      - feat/driveUpload # Trigger the workflow on push to the feat/driveUpload branch

jobs:
  build:
    name: Build and Test React Native App
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Match the Node.js version used in your project

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Set up Java for Android build
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11" # Java 11 is required for modern Android builds

      # Step 5: Install Android SDK
      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O commandlinetools.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          unzip -q commandlinetools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      # Step 6: Build the APK
      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease

      # Step 7: Upload APK as a build artifact (optional)
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
